### PR TITLE
feat: Add support for in-document recipe schemas if present

### PR DESCRIPTION
**Pull request by julianpoy**
This adds support for schema.org recipe schemas if present within the document. See documentation here:

https://schema.org/Recipe

https://developers.google.com/search/docs/data-types/recipe

### CODE REVIEW

**Comment by ajmueller** [comment]
@julianpoy this is ajmueller from Reddit who suggested the feature (I’m sure you never would have guessed with my username 😬). You’re speedy!

If you need some recipes to test, my wife has a blog where she posts recipes. They’re generated in Schema with a generator that I built for her (https://generaterecipecard.com/).

* Example with one section of ingredients - https://www.wholesome.health/blog/easy-overnight-oats-recipe
* Example with two sections of ingredients - https://www.wholesome.health/blog/gluten-free-chickpea-crust-pizza

The sections shouldn’t matter because the Schema structure isn’t changed, but still worth testing extra examples 😊

Keep up the great work!

**Comment by julianpoy** [comment]
@ajmueller Thanks for the links. It doesn't look like either of those actually contain a `Recipe` type schema. I see only `Article` and `WebSite` types.

`[...document.querySelectorAll('script[type="application/ld+json"]')].forEach(e => console.log(JSON.parse(e.innerText)))`

**Comment by julianpoy** [comment]
Looks like this is all working on several websites I've navigated to from Google, both with `Recipe` type schemas directly, as well as embedded within a `Graph` type schema.

**Comment by ajmueller** [comment]
@julianpoy that’s odd. Sorry if I misdirected you on that. I’ll have to check my wife’s site and see what’s going on; perhaps Squarespace is doing something to the markup when she pastes it in. Unfortunately I won’t be able to for a few days as we’re dealing with power outages and ice storms where we live 😬

**Pull request merged**
